// public/elements/examples/angular/src/app/api/api.component.ts
import { Component } from '@angular/core';

import { environment } from '../../environments/environment';

@Component({
  selector: 'app-api',
  templateUrl: './api.component.html',
})
export class ApiComponent {
  apiDescriptionUrl = 'https://raw.githubusercontent.com/interserver/mailbaby-api-spec/master/swagger.yaml';
  basePath = environment.basePath ? `${environment.basePath}/zoom-api` : 'zoom-api';
}

// public/elements/examples/react-cra/src/components/API.tsx
import '@stoplight/elements/styles.min.css';

import { API } from '@stoplight/elements';
import React from 'react';

export const StoplightAPI: React.FC = () => {
  return (
    <API
      basePath="zoom-api"
      apiDescriptionUrl="https://raw.githubusercontent.com/interserver/mailbaby-api-spec/master/swagger.yaml"
    />
  );
};
